name: notes
description: "Demo notes app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  bloc: ^9.0.0
  meta: ^1.16.0
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  easy_localization: ^3.0.7+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0
  flutter_lints: ^5.0.0
  build_runner: any
flutter:
  generate: true
  assets:
    - assets/translations/
  uses-material-design: true

